dibujantes/urls.py
from django.urls import path
from .views import (
    principal,
    busqueda_proyecto,
    retorno_busqueda,
    crearObra,
    buscar,
    creacion,
)

urlPathName = 'dibujantes/'

urlpatterns = [
    path(urlPathName, principal, name= 'principal'),
    path(urlPathName+'busqueda/', busqueda_proyecto, name= 'busqueda'),
    path(urlPathName+'buscar/', buscar, name= 'buscar'),
    path(urlPathName+'dashboard/', retorno_busqueda, name= 'dashboard'),
    path(urlPathName+'crear/', crearObra, name= 'crear'),
    path(urlPathName+'creacion/', creacion, name= 'creacion'),
]

seguimiento_proyectos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import menuInicio
from dibujantes.views import principal

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', principal, name='index'),
    path('', include(('dibujantes.urls', 'dibujantes'), namespace='dibujantes'))

] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)# static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dibujantes/models.py
from django.db import models

# Create your models here.
class ProyectosDibujantes(models.Model):
    consecutivo_planos = models.CharField(max_length=30)
    cotizacion = models.IntegerField(default=0)
    version = models.CharField(max_length=255)
    fecha_ingreso = models.DateField()
    prioridad = models.CharField(max_length=15)
    dibujante = models.CharField(max_length=60)
    cliente_interno = models.CharField(max_length=50)
    cliente_externo = models.CharField(max_length=50)
    zona_venta = models.CharField(max_length=60)
    descripcion_proyecto = models.TextField(max_length=600)
    grado_complejidad = models.CharField(max_length=60)
    visita_campo = models.CharField(max_length=60)
    estado = models.CharField(max_length=60)
    fecha_salida = models.DateField(max_length=60)

dibujantes/views.py
from urllib import request
from django.shortcuts import render, get_object_or_404
from django.http import  Http404
from django.http import HttpResponse

#Rest Framework
from rest_framework.decorators import api_view
from rest_framework.response import Response

#Apps
from .models import ProyectosDibujantes
from .serializers import ProyectoDibujanteSerializer

bd = [
    {
        'title': 'Mont Blanc',
        'photo': 'https://picsum.photos/800/600?image=1036',
    },
    {
        'title': 'Mont Blanc',
        'photo': 'https://picsum.photos/800/600?image=1036',
    },
    {
        'title': 'Mont Blanc',
        'photo': 'https://picsum.photos/800/600?image=1036',
    },
]

# Create your views here.
def principal(request):
    return render(request, 'dibujantes/principal.html')


def busqueda_proyecto(request):
    return render(request, 'dibujantes/busqueda.html')

#@api_view(['GET'])
def buscar(request):
    #print(request.GET['busqueda'])
    #print(request.GET['parametro'])
    if 'parametro' in request.GET:
        print(request.GET['parametro'])
        busqueda= request.GET['busqueda']
        parametro = request.GET['parametro']

        dibujante_asignado=''
        cliente_asignado=''
        cotizacion_asignada=''
        descripcion=''

        if parametro == 'Dibujante':
            #dibujante_asignado = busqueda
            descripcion = busqueda
        elif parametro == 'Cliente':
            cliente_asignado = busqueda
        elif parametro == '# Cotizacion':
            cotizacion_asignada = busqueda
            
        #try:   
        busqueda = ProyectosDibujantes.objects.filter(dibujante__contains=dibujante_asignado, cliente_externo__contains= cliente_asignado,cotizacion__contains=cotizacion_asignada,descripcion_proyecto__contains= descripcion  )
        # print(busqueda)
            #get_object_or_404(ProyectosDibujantes, dibujante__contains=dibujante_asignado, cliente_externo__contains= cliente_asignado,cotizacion=cotizacion_asignada)
        #except:
        #    raise Http404("Solicitud no encontrada, verifique e intente nuevamente")
        # print('this')
    else:
        busqueda = ProyectosDibujantes.objects.all()
        # print('that')
    # print(busqueda)
    return render(request, 'dibujantes/dashboard.html', {'busqueda': busqueda})

def retorno_busqueda(request):
    return render(request, 'dibujantes/dashboard.html', {'bd': bd})

def crearObra(request):
    return render(request, 'dibujantes/form_obra.html')

@api_view(['POST'])
def creacion(request):
    serializer = ProyectoDibujanteSerializer(data = request.data)
    serializer.is_valid(raise_exception=True)
    info =serializer.save()

    return Response(ProyectoDibujanteSerializer(info).data)

seguimiento_proyectos/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def menuInicio(request):
    return render(request, 'inicio.html')

templates/dibujantes/busqueda.html
{% extends 'index.html' %}
    
    {% block container %}
    <div class="container p-5 " >

        <h4 class="mb-3">Buscar Dashboard</h4>
        <form method="GET" action="{% url 'dibujantes:buscar' %}">
            <div class="row g-3">
                <input class="col-sm-6" type="text" name="busqueda" placeholder="busqueda" required>
                
                <div class="col-sm-3">
                    <select class="form-select " name="parametro" id="" required>
                        <option value="">Seleccionar...</option>
                        <option>Cliente</option>
                        <option>Dibujante</option>
                        <option># Cotizacion</option>
                    </select>
                </div>
            </div>
            <hr class="my-4">
            <button class="w-100 btn btn-primary btn-md" type="submit">Buscar</button>
        </form>
        <a class="btn btn-outline-warning mt-2 w-100" href="{% url 'dibujantes:principal' %}"> Regresar a pagina principal</a>
    </div>
    {% endblock container %}

templates/dibujantes/dashboard.html
{% extends "index.html" %}

{% block container %}
          
    <div class="table-responsive">
        {% comment %} <div class="col align-self-start"> {% endcomment %}
            <a class="btn btn-warning  mt-4 w-100" href="{% url 'dibujantes:principal' %}"> Regresar a pagina principal</a>
            <a class="btn btn-info  mt-4 w-100" href="{% url 'dibujantes:busqueda' %}"> Realizar otra busqueda</a>
            <hr class="mb-4">
            <table class="table table-striped table-hover table-bordered align-middle">
                <thead>
                    <tr>
                        <th scope="col">consecutivo_planos</th>
                        <th scope="col">cotizacion</th>
                        <th scope="col">version</th>
                        <th scope="col">fecha_ingreso</th>
                        <th scope="col">prioridad</th>
                        <th scope="col">dibujante</th>
                        <th scope="col">cliente_interno</th>
                        <th scope="col">cliente_externo</th>
                        <th scope="col">zona_venta</th>
                        <th scope="col">descripcion_proyecto</th>
                        <th scope="col">grado_complejidad</th>
                        <th scope="col">visita_campo</th>
                        <th scope="col">estado</th>
                        <th scope="col">fecha_salida</th>
                    </tr>
                </thead>    
                <tbody>
                    {% for rows in busqueda  %}
                    <tr>
                        <td>{{rows.consecutivo_planos}}</td>
                        <td>{{rows.cotizacion}}</td>
                        <td>{{rows.version}}</td>
                        <td>{{rows.fecha_ingreso}}</td>
                        <td>{{rows.prioridad}}</td>
                        <td>{{rows.dibujante}}</td>                    
                        <td>{{rows.cliente_interno}}</td>
                        <td>{{rows.cliente_externo}}</td>
                        <td>{{rows.zona_venta}}</td>
                        <td>{{rows.descripcion_proyecto}}</td>
                        <td>{{rows.grado_complejidad}}</td>
                        <td>{{rows.visita_campo}}</td>
                        <td>{{rows.estado}}</td>
                        <td>{{rows.fecha_salida}}</td>
                    </tr>
                    {% endfor %}             
                </tbody>
                
            </table>
        {% comment %} </div> {% endcomment %}
    </div>
{% endblock %}

templates/dibujantes/form_obra.html
{% extends 'index.html' %}

{% block container %}
    {% comment %} <div class="row g-5">
        <form action="" method="POST">
            <input type="text" placeholder="Consecutivo Planos" required=true >
            <input type="text" placeholder="Consecutivo Planos" required=true >
            <input type="text" placeholder="Consecutivo Planos" required=true >
            <input type="text" placeholder="Consecutivo Planos" required=true >
            <button></button>
        </form> {% endcomment %}
        <div class="col-md-10 col-lg-10 ps-5">
          <h4 class="mb-3">Ingresar Obra</h4>
          <form class="needs-validation" action="{% url 'dibujantes:creacion' %}" method="POST" >
            {% csrf_token %}
            <div class="row g-3">

              <div class="col-sm-6">
                <label for="Consecutivo_Planos" class="form-label">Consecutivo Planos</label>
                <input type="text" name="consecutivo_planos" class="form-control" id="" placeholder=""  required >
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
              </div>
  
              <div class="col-sm-6">
                <label for="#_Cotizacion" class="form-label"># Cotizacion</label>
                <input type="text" name="cotizacion" class="form-control" id="" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>

              <div class="col-sm-6">
                <label for="Version" class="form-label"># Version</label>
                <input type="text" name="version" class="form-control" id="" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>

              <div class="col-sm-6">
                <label for="Fecha_ingreso" class="form-label">Fecha ingreso</label>
                <input type="date" name="fecha_ingreso" class="form-control" id="" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>

              <div class="col-sm-6">
                <label for="Prioridad" class="form-label">Prioridad</label>
                <input type="text" name="prioridad" class="form-control" id="" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>

              <div class="col-sm-6">
                <label for="Dibujante" class="form-label">Dibujante</label>
                <input type="text" name="dibujante" class="form-control" id="" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>

              <div class="col-sm-6">
                <label for="Cliente_interno" class="form-label">Cliente interno</label>
                <input type="text" name="cliente_interno" class="form-control" id="" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>

              <div class="col-sm-6">
                <label for="Cliente_externo" class="form-label">Cliente externo</label>
                <input type="text" name="cliente_externo" class="form-control" id="" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>
              <div class="col-sm-6">
                <label for="Zona_venta" class="form-label">Zona venta</label>
                <input type="text" name="zona_venta" class="form-control" id="" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>

              <div class="col-sm-6">
                <label for="Grado_complejidad" class="form-label">Grado de complejidad</label>
                <input type="text" name="grado_complejidad" class="form-control" id="" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>
              <div class="col-sm-12">
                <label for="Descripcion_proyecto" class="form-label">Descripcion del proyecto</label>
                {% comment %} <input type="text" class="form-control" id="lastName" placeholder="" value="" required> {% endcomment %}
                <textarea class="form-control" name="descripcion_proyecto" aria-label="With textarea"></textarea>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>

              <div class="col-md-5">
                <label for="country" class="form-label">Visita de campo</label>
                <select class="form-select" name="visita_campo" id="" required>
                  <option value="" >Seleccionar...</option>
                  <option value="No">No</option>
                  <option value="Si">Si</option>
                </select>
                <div class="invalid-feedback">
                  Please select a valid country.
                </div>
              </div>
  
              <div class="col-md-4">
                <label for="state" class="form-label">State</label>
                <select class="form-select" name="estado"id="" required>
                  <option value="">Seleccionar...</option>
                  <option >EN PROCESO</option>
                  <option>TERMINADA</option>
                </select>
                <div class="invalid-feedback">
                  Please provide a valid state.
                </div>
              </div>
  
              <div class="col-md-3">
                <label for="zip" class="form-label">Fecha de salida</label>
                <input type="date" name="fecha_salida" class="form-control" id="" placeholder="" required>
                <div class="invalid-feedback">
                  Zip code required.
                </div>
              </div>
            </div>

            <hr class="my-4">
  
            <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
          </form>
          <a class="btn btn-warning btn-lg my-3 w-100" href="{% url 'dibujantes:principal' %}"> Regresar a pagina principal</a>
        </div>
      </div>


{% endblock container %}

templates/dibujantes/principal.html
{% extends 'index.html' %}

{% block container %}
    <div class="container-fluid py-3 d-flex flex-column">
      <a class="btn btn-outline-primary my-2" href="{% url 'dibujantes:buscar' %}">Ver todos</a>
      <a class="btn btn-outline-primary my-2" href="{% url 'dibujantes:busqueda' %}">Buscar proyecto</a>
      <a class="btn btn-outline-primary my-2" href="{% url 'dibujantes:crear' %}">Crear proyecto</a>
    </div>
{% endblock container %}

templates/footer.html
<footer class=" mt-auto bg-light text-center text-lg-start">
    
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2022 Copyright:
      {% comment %} <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a> {% endcomment %}
        <span>Daniel Salazar</span>
    </div>
    <!-- Copyright -->
  </footer>

templates/header.html
{% comment %} {% load static %} {% endcomment %}
<header>
  <!-- As a heading -->

    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1 ps-2">Dashboard de Dibujantes</span>
    </nav>

  

</header>

templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head_content %}
        {% endblock head_content %}

        {% load static %}
        <!-- <base href="{% static '/' %} > -->
        {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"> {% endcomment %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <base href="{% static '/' %}">
        
        <title>Document</title>
    </head>
    <body class="d-flex flex-column min-vh-100">
        {% include "header.html" %}
        <div >
            {% block container %}
            
            
            {% endblock container %}
        </div>
        {% include 'footer.html' %}
    </body>
</html>

templates/inicio.html
<a href="">Buscar proyecto</a>